# Multi-Stage Hardened Production Dockerfile
# Generated by VEYRA Universal Orchestrator

FROM node:22-alpine AS base
WORKDIR /app
ENV NODE_ENV=production
RUN apk add --no-cache dumb-init

# Copy package descriptors if present
COPY package*.json ./
RUN if [ -f package.json ]; then npm ci --only=production || true; fi

# Copy application code
COPY . .

# Run as non-root unprivileged user for container security
USER node

EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD node -e "require('http').get('http://localhost:3000/api/health', (r) => { if (r.statusCode !== 200) process.exit(1); })"

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["node", "server.mjs"]
